meta_product_name: "Lulubio"
meta_title: "Lulubio - Alimentation et bien-être"
meta_description: "Vente de produits bio et locaux à Casteljaloux (47)."
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
